### ISSUE TITLE
TypeError when upgrading to versions 1.x

### ISSUE THREAD

**Issue by y26805** [nekitdev/versions#2]
Hi, I am currently using versions 0.10.0.

When trying to upgrade to v1.x (i.e. 1.0.0 and 1.1.0), i am getting the following error in my code:
```
TypeError: Version.__init__() got an unexpected keyword argument 'prerelease'
```

Any idea why this happens?

Environment: Python 3.10

**Comment by y26805** [comment]
I think it's because I have a line that goes
```
assert Version.parse("1.0.0-dev") == Version(1, 0, 0, prerelease="dev")
```
which fails in v1.x

**Comment by nekitdev** [comment]
Hello. The thing is, version 1.0.0 has a complete rewrite of the previous version, so many things got removed. Please refer to the documentation for the API reference and related things.

As for the case you have shown, you can do the following:

```python
from versions import DevTag, Version

assert Version.parse("1.0.0-dev") == Version.from_parts(1, 0, 0, dev=DevTag("dev", 0))
```
